// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClientCreate = {
    name: string;
    email: string;
    phone?: (string | null);
    postal_address?: (string | null);
    postal_code?: (string | null);
    town?: (string | null);
};

export type ClientPublic = {
    name: string;
    email: string;
    phone?: (string | null);
    postal_address?: (string | null);
    postal_code?: (string | null);
    town?: (string | null);
    id: string;
};

export type ClientsPublic = {
    data: Array<ClientPublic>;
    count: number;
};

export type ClientUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    postal_address?: (string | null);
    postal_code?: (string | null);
    town?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PoliciesPublic = {
    data: Array<PolicyPublic>;
    count: number;
};

export type PolicyCreate = {
    policy_number: string;
    type: PolicyType;
    provider: string;
    start_date: string;
    end_date?: (string | null);
    status?: PolicyStatus;
    client_id: string;
};

export type PolicyPublic = {
    policy_number: string;
    type: PolicyType;
    provider: string;
    start_date: string;
    end_date?: (string | null);
    status?: PolicyStatus;
    client_id: string;
    id: string;
};

export type PolicyStatus = 'ACTIVE' | 'EXPIRED' | 'CANCELLED';

export type PolicyType = 'HEALTH' | 'LIFE' | 'AUTO' | 'HOME';

export type PolicyUpdate = {
    policy_number?: (string | null);
    type?: (PolicyType | null);
    provider?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: (PolicyStatus | null);
    client_id?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ClientsReadClientsData = {
    limit?: number;
    skip?: number;
};

export type ClientsReadClientsResponse = (ClientsPublic);

export type ClientsCreateClientData = {
    requestBody: ClientCreate;
};

export type ClientsCreateClientResponse = (ClientPublic);

export type ClientsReadClientData = {
    id: string;
};

export type ClientsReadClientResponse = (ClientPublic);

export type ClientsUpdateClientData = {
    id: string;
    requestBody: ClientUpdate;
};

export type ClientsUpdateClientResponse = (ClientPublic);

export type ClientsDeleteClientData = {
    id: string;
};

export type ClientsDeleteClientResponse = (void);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PoliciesReadPoliciesData = {
    limit?: number;
    skip?: number;
};

export type PoliciesReadPoliciesResponse = (PoliciesPublic);

export type PoliciesCreatePolicyData = {
    requestBody: PolicyCreate;
};

export type PoliciesCreatePolicyResponse = (PolicyPublic);

export type PoliciesReadPolicyData = {
    id: string;
};

export type PoliciesReadPolicyResponse = (PolicyPublic);

export type PoliciesUpdatePolicyData = {
    id: string;
    requestBody: PolicyUpdate;
};

export type PoliciesUpdatePolicyResponse = (PolicyPublic);

export type PoliciesDeletePolicyData = {
    id: string;
};

export type PoliciesDeletePolicyResponse = (void);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (void);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (void);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);